# Base image for production
FROM node:20-slim AS production

# Define app path inside the container
ARG APP_PATH=/opt/outline
WORKDIR $APP_PATH

# Set production environment variables
ENV NODE_ENV=production
ENV PORT=3000

# Copy the pre-built application from your local machine
COPY ./build $APP_PATH

# Expose the application port
EXPOSE 3000

# Start the application
CMD ["node", "./build/server/index.js"]
